#!/bin/csh

#'input' is a one-line file with a four-character word. Just do 'echo "pdbb" > input' !
set directory = `head -1 input` 
set MKDIR=/bin/mkdir

	foreach f("$directory")
#	$MKDIR ../$f'PAIR'
	$MKDIR ../$f'PAIROR'
	$MKDIR ../$f'zpot4a'
	$MKDIR ../$f'pdborienrev4/'
	$MKDIR ../$f'pdborienrev/'
	$MKDIR ../$f'goodraorienrev'
	$MKDIR ../$f'goodr1aorienrev'
	$MKDIR ../$f'qzmediumsummary'
	$MKDIR ../$f'qzmediumtemplates'
	$MKDIR ../$f'qzmediumcontacts'
end 
