#!/bin/csh
alias rm rm
touch finish_best
set nfiles = `head -1 nruns` #query-sequences were divided into packs of 10. nfiles=number of packs
echo $nfiles
set pdbn = `head -1 input` #prefix
set pdb = `head -1 input2` #prefix
#create STRUCTURE_rap3orienrev, which contains all STRUCTURE_selectedrap3orienrevpdbbXX files
./summaryrap3orienrev
echo 'preparing STRUCTURE_rap3orienrev'
sleep 20
echo 'number of files in STRUCTURE_rap3orienrev'
head -1 STRUCTURE_rap3orienrev #this is nruns again

# init finish_$i files
foreach i(best verygood fair bad)
    touch finish_$i
    rm  finish_$i
    echo '-1'>finish_$i
end 

#run analysis of results
echo 'now running analysis'
foreach i(best verygood fair bad)
    ./$i & #execute $i in background
    set o = `head -1 finish_$i`
    12: #weird loop to wait until ./$i & has finished
    echo $i
    head -1 finish_$i
    set o = `head -1 finish_$i`
    if("$o" == "-1")then
	echo 'working on '$i
	set o = `head -1 finish_$i`
	sleep 10
	goto 12
    endif
    echo $i' is finished'
    echo ' '
end 

#
echo 'NOW ANALYZING RESULTS'
echo 'listbest'
head -1 listbest

#insert results of "wc listbad" as first line of listbad itself
mv listbad s1
cat s1|wc
cat s1|wc>o1
cp o1 listbad
cat s1>>listbad

foreach i(verygood fair)
    echo $i
    head -1 list_$i
end

echo bad
head -1 listbad
echo 'analysis finished'
