#!/bin/csh
alias rm rm
touch runsum
rm runsum
touch runsum

set pdbn = `head -1 input`
set pdb = `head -1 input2`

set nfiles = `head -1 nruns`

set o = 1

while ($o <= 2)

if("$o" == 1)then
set p1 = 'pairpsi'
set p2 = 'pairorpsi'
set p3 = 'dummy'
endif

if("$o" == 2)then
set p1 = 'raorienrev'
set p2 = 'rap2orienrev'
set p3 = 'rap3orienrev'
endif

foreach p($p1 $p2 $p3)

if( "$p" == "dummy")then
goto 100
endif


echo $o>>runsum
echo $p>>runsum

set f = 1

while ($f <= "$nfiles")

if($f <= 99)then
set g = "$pdbn"
else
set g = "$pdb"
endif

if($f <= 9)then
touch  completed$p$g'_'$f
rm     completed$p$g'_'$f
touch  completed$p$g'_'$f
endif

if($f > 9)then
touch  completed$p$g$f
rm     completed$p$g$f
touch  completed$p$g$f
endif

@ f ++
end 

bsub -q critical-ibm -J ""$p"[1-"$nfiles"]" -i "nametarg%I" ./$p >>runsum 

1:

set s = 0

set f = 1

while ($f <= "$nfiles")

if($f <= 99)then
set g = "$pdbn"
else
set g = "$pdb"
endif

if($f <= 9)then
set file = completed$p$g'_'$f
else
set file = completed$p$g$f
endif

if !(-z  $file) then
echo 'file '$f' is created'>>runsum
@ s ++
endif
#
@ f ++

end

if("$s" < "$nfiles") then
sleep 30
echo 'continuing to check '$p' pass'>>runsum
goto 1
else
echo 'end of '$p' pass'>>runsum
endif

end
100:
@ o ++
end
