#!/bin/bash

#'input' is a one-line file with a four-character word. Just do 'echo "pdbb" > input' !
dirs=`head -1 input` 
otherdirs="PAIR PAIROR zpot4a pdborienrev4 pdborienrev goodraorienrev qzmediumsummary qzmediumtemplates qzmediumcontacts goodr1aorienrev"
for f in $dirs; do
    for g in $otherdirs; do
	/bin/mkdir -p ../${f}$g
    done
done



