#!/bin/csh
cp ../threadingpdb200jul07/3590 .
cp ../threadingpdb200jul07/3590aln .
cp ../threadingpdb200jul07/mtx .
cp ../threadingpdb200jul07/direct .
cp ../threadingpdb200jul07/e10 .
cp ../threadingpdb200jul07/e10aln .
cp ../threadingpdb200jul07/input .
cp ../threadingpdb200jul07/input2 .
cp ../threadingpdb200jul07/namesize .
cp ../threadingpdb200jul07/*f .
cp ../threadingpdb200jul07/secon .
cp ../threadingpdb200jul07/seconend .
cp ../threadingpdb200jul07/setupf .
cp ../threadingpdb200jul07/homedir .
cp ../threadingpdb200jul07/templatedir .
cp ../threadingpdb200jul07/arraysub* .
cp ../threadingpdb200jul07/sumjulyrap3orienrev  .
